using System.Security.Cryptography;
using MechanicAI.Application.Abstractions;

namespace MechanicAI.Infrastructure.Platform;

/// <summary>
/// Stores uploaded files under the data directory with random names (the original name is
/// kept only in the database), so user-supplied file names never become paths.
/// </summary>
public sealed class LocalFileStore(IAppPaths paths) : IFileStore
{
    public const long MaxFileBytes = 512L * 1024 * 1024;

    public async Task<StoredFile> SaveAsync(Stream content, string originalFileName, FileArea area, CancellationToken ct)
    {
        var extension = Path.GetExtension(originalFileName).ToLowerInvariant();
        if (extension.Length > 10 || extension.Any(c => !char.IsAsciiLetterOrDigit(c) && c != '.')) extension = ".bin";

        var storedName = $"{Guid.CreateVersion7():N}{extension}";
        var fullPath = Path.Combine(Directory(area), storedName);
        using var sha = IncrementalHash.CreateHash(HashAlgorithmName.SHA256);
        long total = 0;
        var buffer = new byte[81920];
        await using (var output = new FileStream(fullPath, FileMode.CreateNew, FileAccess.Write, FileShare.None, 81920, useAsync: true))
        {
            int read;
            while ((read = await content.ReadAsync(buffer, ct)) > 0)
            {
                total += read;
                if (total > MaxFileBytes)
                {
                    output.Close();
                    File.Delete(fullPath);
                    throw new InvalidDataException($"File exceeds the {MaxFileBytes / (1024 * 1024)} MB limit.");
                }

                sha.AppendData(buffer, 0, read);
                await output.WriteAsync(buffer.AsMemory(0, read), ct);
            }
        }

        return new StoredFile(storedName, total, Convert.ToHexStringLower(sha.GetHashAndReset()));
    }

    public Stream OpenRead(string storedFileName, FileArea area) =>
        new FileStream(GetFullPath(storedFileName, area), FileMode.Open, FileAccess.Read, FileShare.Read, 81920, useAsync: true);

    public string GetFullPath(string storedFileName, FileArea area)
    {
        // Defense in depth: stored names are generated by this class, but never allow traversal.
        var name = Path.GetFileName(storedFileName);
        return Path.Combine(Directory(area), name);
    }

    public Task DeleteAsync(string storedFileName, FileArea area, CancellationToken ct)
    {
        var path = GetFullPath(storedFileName, area);
        if (File.Exists(path)) File.Delete(path);
        return Task.CompletedTask;
    }

    private string Directory(FileArea area) => area switch
    {
        FileArea.Documents => paths.DocumentsDirectory,
        FileArea.Media => paths.MediaDirectory,
        _ => paths.ExportsDirectory,
    };
}
